Make sure we have at least rsync 3.0.

diff --git a/bin/nikola b/bin/nikola
--- a/bin/nikola
+++ b/bin/nikola
@@ -55,6 +55,10 @@ usage() {
   exit 2
 }
 
+if ! rsync --version | grep -q "version 3"; then
+  abort "rsync version 3 or higher required"
+fi
+
 while getopts :hna:b:e: o; do
   case "$o" in
     a) POST_SCRIPT="$OPTARG" ;;
